# Moon-Counter Config 
# See config docs: https://mini.moonlab.top/post/20231224-14/
host: counter.moonlab.top
listen: 3800
img_theme: rule34
cors: true
hostnames: 
  - moonlab.top
  - mini.moonlab.top
  - github.com

error_log: error.log

db:
  type: sqlite
  dbname: moon.db
  host:
  username:
  password:

admin:
  enable: false
  path: /admin
  passphrase: