# Moon-Counter Config 
# See config docs: https://mini.moonlab.top/post/20231224-14/
host: counter.moonlab.top
listen: 3800
cors: true
img_theme: rule34
hostnames: 
  - moonlab.top
  # Remove localhost in production
  - localhost

error_log: error.log

db:
  type: sqlite
  dbname: moon.db
  host:
  username:
  password:

admin:
  enable: false
  path: /admin
  # Use password generator
  password: 